config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :magazines do
    member do
      get 'posts', to: 'magazines#posts'

      post 'subscribe', to: 'magazines#subscribe'
      delete 'subscribe', to: 'magazines#unsubscribe'
    end
  end

  resources :posts do

    post 'new_thread', on: :collection
    member do
      post 'upvote'
      post 'downvote'
      post 'boost'
      delete 'boost', action: :unboost
    end


    member do
      get 'sort_comments', to: "comments#sort"
      get 'sort_posts', to: "posts#sort"

    end
    resources :comments do

      member do
        # put 'upvote', on: :member
        # put 'downvote', on: :member
        post 'upvote'
        delete 'upvote'
        post 'downvote'
        delete 'downvote'

        get 'edit'
      end

    end
    collection do
    get 'new_link'
    get 'new_thread'
    get 'sort'
    get 'search', to: 'posts#search'

    end
  end


  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id', to: 'users/users#show', as: :user
    get 'users/:id/edit', to: 'users/users#edit', as: :edit_user
    patch '/users/:id', to: 'users/users#update'

    get 'users', to: 'users/users#index'
    get 'users/:id/comments', to: 'users/users#user_comments'
    get 'users/:id/posts', to: 'users/users#user_posts'
    get 'users/:id/boosts', to: 'users/users#user_boosts'
    put 'users/:id', to: 'users/users#update'

  end

  # Añadir la ruta para el perfil del user
  #get 'profile', to: 'users/users#show', as: 'profile'
  post 'posts', to: 'posts#create'
  delete 'posts/:id/', to: 'posts#destroy'
  put 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show'
  post 'posts/:id/upvote', to: 'posts#upvote'
  delete 'posts/:id/upvote', to: 'posts#upvote'
  put 'posts/:id/boost', to:'posts#boost'
  delete 'posts/:id/boost', to:'posts#unboost'
  post 'posts/:id/downvote', to: 'posts#downvote'
  delete 'posts/:id/downvote', to: 'posts#downvote'
  get 'posts/search', to: 'posts#search'


end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comment_votes, dependent: :destroy
  has_and_belongs_to_many :magazines
  has_many :boosts, dependent: :destroy
  has_one_attached :avatar
  has_one_attached :background
  before_create :set_api_key

  def comments_num
    comments.count
  end

  def posts_num
    posts.count
  end

  def boosts_num
    boosts.count
  end

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end

  def generate_api_key
    self.api_key = SecureRandom.base58(24)
  end

  def set_api_key
    generate_api_key if api_key.blank?
  end

  def save_image_to_s3(image, image_type)
    name = File.basename(image.path)
    s3 = Aws::S3::Resource.new(
      region: 'us-east-1',
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      session_token: ENV['AWS_SESSION_TOKEN']
    )
    bucket = s3.bucket('talkify-bucket')
    obj = bucket.object("#{image_type}/#{name}")
    obj.upload_file(image.path)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_google(**from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/users/users_controller.rb
# app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :set_votes_hash
  before_action :set_user
  before_action :set_target_user, only: [:show, :user_comments, :user_posts, :user_boosts, :update]

  def index
    @users = User.all
    render json: @users.as_json(except: [:uid, :api_key])
  end

  def show
    params[:view] ||= 'threads'
    @posts = @user_target.posts.order(created_at: :desc)
    @comments = @user_target.comments.order(created_at: :desc)

    # Calculate the counts
    comments_count = @user_target.comments.count
    posts_count = @user_target.posts.count

    # Only calculate boosts_count if the user is the same as @user
    boosts_count = @user == @user_target ? Boost.where(user: @user_target).count : nil

    @user = User.find(params[:id])


    set_votes_hash
    respond_to do |format|
      format.html
      format.json do
        user_json = @user_target.as_json(except: [:uid, :api_key]).merge({
          comments_count: comments_count,
          posts_count: posts_count,
          avatar: @user_target.avatar.attached? ? url_for(@user_target.avatar) : nil,
          background: @user_target.background.attached? ? url_for(@user_target.background) : nil

        })

        user_json[:boosts_count] = boosts_count unless boosts_count.nil?

        render json: user_json
      end
    end
  end

  def set_votes_hash
    if user_signed_in?
      @votes_hash = current_user.votes.index_by(&:post_id).transform_values(&:vote_type)
      @boosted_posts_ids = current_user.boosts.pluck(:post_id)
      @boosted_posts = Post.where(id: @boosted_posts_ids)
      @comment_votes_hash = current_user.comment_votes.index_by(&:comment_id).transform_values(&:vote_type)

    else
      @votes_hash = {}
      @boosted_posts = {}
      @comment_votes_hash = {}

    end
  end


  def boosted_posts
    @boosted_posts = Boost.where(user: current_user).includes(:post).map(&:post)
  end


  def sort
    @posts = Post.order_by(params[:sort_by])

    case params[:from]
    when "user_show"
      # Asegúrate de definir todas las variables necesarias para esta vista.
      @user = User.find(params[:user_id]) # Asegúrate de pasar el user_id de alguna manera.
      @comments = @user.comments.includes(:post).order(created_at: :desc)
      render 'users/users/show'
    else
      render 'index'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user_params = params[:user].present? ? params[:user] : params

    puts @user.inspect

    respond_to do |format|
      if @user != @user_target
        format.json { render json: { error: "You can only edit your profile", errors: @user.errors }, status: :forbidden }
      else
        if user_params[:avatar].present?
          avatar = user_params[:avatar].is_a?(String) ? parse_image_data(user_params[:avatar]) : user_params[:avatar]
          @user.avatar.attach(avatar)
          @user.save_image_to_s3(avatar, 'avatar') if @user.avatar.attached?
        end
        if user_params[:background].present?
          background_image = user_params[:background].is_a?(String) ? parse_image_data(user_params[:background]) : user_params[:background]
          @user.background.attach(background_image)
          @user.save_image_to_s3(background_image, 'background') if @user.background.attached?
        end
        if user_params[:full_name].present?
          @user.full_name = user_params[:full_name]
        end
        if user_params[:description].present?
          @user.description = user_params[:description]
        end

        if @user.save
          user_hash = @user.attributes.except('updated_at', 'url', 'encrypted_password', 'reset_password_token', 'reset_password_sent_at', 'remember_created_at', 'provider', 'uid').merge({
                   posts_count: @user.posts.count,
                   comments_count: @user.comments.count,
                   boosts_count: @user.boosts.count,
                   avatar: @user.avatar.attached? ? url_for(@user.avatar) : nil,
                   background: @user.background.attached? ? url_for(@user.background) : nil
                 })

          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render json: user_hash }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: { error: "There was an error updating the user.", errors: @user.errors }, status: :unprocessable_entity }
        end
      end
    end
end



  def user_comments
    @user = User.find(params[:id])

    case params[:sort_by]
    when "top"
      @comments = @user.comments
                               .select('comments.*, (comments.upvote - comments.downvote) AS votes_difference')
                               .order('votes_difference DESC')
    when "newest"
      @comments = @user.comments.order(created_at: :desc)
    else
      @comments = @user.comments.order(created_at: :asc)
    end

    respond_to do |format|
      format.html { render 'user/show' }
      format.json { render json: json_with_replies(@comments), status: :ok }
    end
  end

  def user_params
    params.require(:user).permit(:email, :full_name, :description, :uid)
  end

def user_posts
  @user = User.find(params[:id])
  @posts = @user.posts.order_by(params[:sort_by])

  respond_to do |format|
    format.html { render 'user/show' }
    format.json do
      if @posts.present?
        @posts = @posts.map do |post|
          post_json = post.as_json(methods: [:upvotes_count, :downvotes_count, :comments_count], except: [:magazine_id, :user_id]).merge(
            is_upvoted: post.is_upvoted(@user),
            is_downvoted: post.is_downvoted(@user),
            is_boosted: post.is_boosted(@user)
          )

          if post.magazine.present?
            post_json[:magazine] = post.magazine.as_json(only: [:id, :title, :description])
          end

          if post.user.present?
            post_json[:user] = post.user.as_json(only: [:id, :full_name, :email])
          end

          post_json
        end
        render json: { posts: @posts }
      else
        render json: { error: "No posts found" }, status: :not_found
      end
    end
  end
end

def user_boosts
  @user = User.find(params[:id])
  @user_target = @user

  if @user == @user_target
    @boosted_posts = Boost.where(user: @user).includes(:post).map(&:post)
    @boosted_posts = @boosted_posts.map do |post|
      post_json = post.as_json(methods: [:upvotes_count, :downvotes_count, :comments_count], except: [:magazine_id, :user_id]).merge(
        is_upvoted: post.is_upvoted(@user),
        is_downvoted: post.is_downvoted(@user),
        is_boosted: post.is_boosted(@user)
      )

      if post.magazine.present?
        post_json[:magazine] = post.magazine.as_json(only: [:id, :title, :description])
      end
      if post.user.present?
        post_json[:user] = post.user.as_json(only: [:id, :full_name, :email])
      end

      post_json
    end

    response = { "boosted_posts" => @boosted_posts }
    status = :ok
  else
    response = { "error" => "You can only see the boosts of your own user." }
    status = :forbidden
  end

  respond_to do |format|
    format.html { render 'user/show' }
    format.json { render json: response, status: status }
  end
end

  private

  def json_with_replies(comments)
    result = Array(comments).map do |comment|
      comment.as_json(except: [:post_id, :user_id]).merge(
        user: comment.user.as_json(only: [:id, :full_name, :email]),
        post: comment.post.as_json(only: [:id, :title]),
        is_upvoted: comment.is_upvoted(@user),
        is_downvoted: comment.is_downvoted(@user),
        is_author: comment.user == @user,
        replies: Array.wrap(json_with_replies(comment.replies)),
      )
    end

    result.length == 1 ? result.first : result
  end

  def set_user
    if request.headers[:Accept] == "application/json"
      api_key = request.headers[:HTTP_X_API_KEY]

      if api_key.nil?
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      else
        @user = User.find_by_api_key(api_key)
        if @user.nil?
          render :json => { "status" => "403", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
        end
      end
    else
      @user = current_user
    end
  end

  def set_target_user
    @user_target = User.find_by(id: params[:id])
    if @user_target.nil?
      render json: { "error" => "User not found" }, status: :not_found and return
    end
  end

  def parse_image_data(base64_image)
    filename = "upload-image"
    in_content_type, encoding, string = base64_image.split(/[:;,]/)[1..3]

    @tempfile = Tempfile.new(filename)
    @tempfile.binmode
    @tempfile.write Base64.decode64(string)
    @tempfile.rewind

    # for security we want the actual content type, not just what was passed in
    content_type = MIME::Types[in_content_type].first.content_type

    # we will also add the extension ourselves based on the above
    # if it's not gif/jpeg/png, it will fail the validation in the upload model
    extension = MIME::Types[content_type].first.extensions.first
    filename += ".#{extension}" if extension

    ActionDispatch::Http::UploadedFile.new({
                                             tempfile: @tempfile,
                                             content_type: content_type,
                                             filename: filename
                                           })

  end

end

app/views/users/users/_formedit.html.erb
<div class="wotitem">
  <div class="post-header">

    <div class="post-content" style="color: white;">
      <%= form_with(model: @user, method: :patch, local: true, html: { class: "post-form" }) do |form| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> han ocurrido al editar el usuario:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">

          <%= form.text_area :description, rows: 3, class: "form-control" %>
        </div>


        <div class="form-group">
          <%= form.label :full_name, "Nombre del usuario", class: "form-label" %>
          <%= form.text_field :full_name, class: "form-control" %>
        </div>

        <div>
          <%= form.label :avatar, "Avatar", class: "form-label" %>
          <%= form.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>
        </div>
        <p> </p>
        <div>
          <%= form.label :background, "Background image", class: "form-label" %>
          <%= form.file_field :background, accept: "image/jpeg,image/gif,image/png" %>
        </div>
        <p> </p>

        <div class="form-group text-left">
          <%= form.submit "Guardar", class: "btn btn-primary btn-rectangular" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/users/_user.html.erb
  <div class="profile-header">

    <% if @user.background.attached? %>
      <%= image_tag @user.background.variant(resize_to_limit: [1080, 720]), class: "background-banner" %>
    <% end %>

  </div>


  <div class="overlay" style="float: left; display: flex; flex-direction: column; align-items: center;">

    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar.variant(resize_to_limit: [100, 100]), class: "avatar" %>
    <% end %>

    <p style="font-weight: bold; margin-bottom: 5px"><%= @user.full_name %></p>
    <p style="margin: 5px 0;"><%= @user.email %></p>
    <p style="margin-top: 5px;"><%= @user.description %></p>
    <p style="margin-top: 5px;"><%=@user.api_key%></p>


    <div class="user_actions">
      <i style="margin: 5px 5px 5px 5px;" class="fas fa-users"></i> &nbsp 0 &nbsp
    </div>

  </div>

app/views/users/users/edit.html.erb
<div class="wotitem">
  <%= render 'users/users/user' %>
</div>
<div class="sub-navbar wotitem">
  <div>
    <%= link_to "Profile", edit_user_path(@user) %>
  </div>
</div>

  <div class="post-header">
    <!-- Contenido del post -->
    <div class="post-content" style="color: white;">
      <!-- Renderizar el formulario de edición -->
      <%= render 'formedit' %>
    </div>
  </div>

app/views/users/users/show.html.erb
<div class="wotitem profile-header">
    <%= render 'users/users/user' %>
</div>

<div>
  <div class="sub-navbar wotitem">
    <div>
      <%= link_to "Threads", user_path(@user, view: 'threads') %>
      <%= link_to "Comments", user_path(@user, view: 'comments') %>
      <%= link_to "Boosts", user_path(@user, view: 'boost') %>
    </div>
  </div>
</div>

<p> </p>

<body class="wotbody">
  <% if params[:view] == 'threads' %>
    <div class="sub-navbar wotitem">
     <div>
        <%= link_to "Top", sort_posts_path(sort_by: "top") %>
        <%= link_to "Newest", sort_posts_path(sort_by: "newest") %>
        <%= link_to "Commented", sort_posts_path(sort_by: "commented") %>
      </div>
    </div>
    <div id="posts">
      <% @posts.each do |post| %>
          <div>
              <%= render 'posts/post', post: post %>
          </div>
      <% end %>
    </div>
  <% elsif params[:view] == 'comments' %>
    <div id="comments">
      <% @comments.each do |comment| %>
          <div>
              <%= render 'comments/comment', comment: comment, post: comment.post %>
          </div>
      <% end %>
    </div>
  <% elsif params[:view] == 'boost' %>
  <div id="boosts">
    <% @boosted_posts.each do |post| %>
      <div>
        <%= render 'posts/post', post: post %>
      </div>
      <% end %>
  </div>
  <% end %>


</body>