config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :magazines do
    member do
      get 'posts', to: 'magazines#posts'

      post 'subscribe', to: 'magazines#subscribe'
      delete 'subscribe', to: 'magazines#unsubscribe'
    end
  end

  resources :posts do

    post 'new_thread', on: :collection
    member do
      post 'upvote'
      post 'downvote'
      post 'boost'
      delete 'boost', action: :unboost
    end


    member do
      get 'sort_comments', to: "comments#sort"
      get 'sort_posts', to: "posts#sort"

    end
    resources :comments do

      member do
        # put 'upvote', on: :member
        # put 'downvote', on: :member
        post 'upvote'
        delete 'upvote'
        post 'downvote'
        delete 'downvote'

        get 'edit'
      end

    end
    collection do
    get 'new_link'
    get 'new_thread'
    get 'sort'
    get 'search', to: 'posts#search'

    end
  end


  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id', to: 'users/users#show', as: :user
    get 'users/:id/edit', to: 'users/users#edit', as: :edit_user
    patch '/users/:id', to: 'users/users#update'

    get 'users', to: 'users/users#index'
    get 'users/:id/comments', to: 'users/users#user_comments'
    get 'users/:id/posts', to: 'users/users#user_posts'
    get 'users/:id/boosts', to: 'users/users#user_boosts'
    put 'users/:id', to: 'users/users#update'

  end

  # Añadir la ruta para el perfil del user
  #get 'profile', to: 'users/users#show', as: 'profile'
  post 'posts', to: 'posts#create'
  delete 'posts/:id/', to: 'posts#destroy'
  put 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show'
  post 'posts/:id/upvote', to: 'posts#upvote'
  delete 'posts/:id/upvote', to: 'posts#upvote'
  put 'posts/:id/boost', to:'posts#boost'
  delete 'posts/:id/boost', to:'posts#unboost'
  post 'posts/:id/downvote', to: 'posts#downvote'
  delete 'posts/:id/downvote', to: 'posts#downvote'
  get 'posts/search', to: 'posts#search'


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent_comment, class_name: "Comment", optional: true
  has_many :replies, class_name: "Comment", foreign_key: :parent_comment_id, dependent: :destroy
  has_many :comment_votes, dependent: :destroy

  after_initialize :set_default_values

  validates :body, presence: true, length: { minimum: 1 }


  def self.order_by(sort_by)
      case sort_by
      when "top"
        order(upvotes_count: :desc)
      when "newest"
        order(created_at: :desc)
      when "oldest"
        order(created_at: :asc)
      else
        order(created_at: :desc) # Ordenar por defecto por fecha de creación
      end
  end

  def upvotes_count
    comment_votes.where(vote_type: 'upvote').count
  end

  def downvotes_count
    comment_votes.where(vote_type: 'downvote').count
  end

  def is_upvoted(user)
    comment_votes.where(vote_type: 'upvote', user_id: user.id).exists?
  end

  def is_downvoted(user)
    comment_votes.where(vote_type: 'downvote', user_id: user.id).exists?
  end

  private

  def set_default_values
      self.upvote ||= 0
      self.downvote ||= 0
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_votes_hash
  before_action :set_user
  before_action :set_comment, except: [:sort, :new, :create, :index]
  before_action :set_post, only: [:sort, :edit]

  def set_votes_hash
    if user_signed_in?
      @comment_votes_hash = current_user.comment_votes.index_by(&:comment_id).transform_values(&:vote_type)
      @votes_hash = current_user.votes.index_by(&:post_id).transform_values(&:vote_type)
      @boosted_posts = current_user.boosts.pluck(:post_id)
    else
      @votes_hash = {}
      @comment_votes_hash = {}
      @boosted_posts = {}

    end
  end

def upvote

    ActiveRecord::Base.transaction do

      @comment_vote = @comment.comment_votes.find_or_initialize_by(user: @user)
      if request.request_method == "POST"
        if @comment_vote.new_record?
          @comment_vote.vote_type = 'upvote'
          @comment_vote.save!
          @comment.upvote += 1
          @comment.save!
        elsif @comment_vote.vote_type == 'downvote'
          @comment_vote.destroy!
          @comment.upvote += 1
          @comment.downvote -= 1
          @comment.save!
          @comment.comment_votes.create!(user: @user, vote_type: 'upvote')
        elsif @comment_vote.vote_type == 'upvote'
          @comment_vote.destroy!
          @comment.upvote -= 1
          @comment.save!
        end
      elsif request.request_method == "DELETE"
        if @comment_vote.new_record?
          render :json => { "status" => "404", "error" => "No upvote found to delete." }, status: :forbidden and return
        elsif @comment_vote.vote_type == 'upvote'
          @comment_vote.destroy!
          @comment.upvote -= 1
          @comment.save!
        end
      end
      end


  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    #format.json { render json: { "status" => "200", "message" => "Vote successfully added." }, status: :ok }
    format.json { render json: json_with_replies(@comment) , status: :ok }
  end
end

def downvote

    ActiveRecord::Base.transaction do
      @comment_vote = @comment.comment_votes.find_or_initialize_by(user: @user)
      if request.request_method == "POST"
        if @comment_vote.new_record?
          @comment_vote.vote_type = 'downvote'
          @comment_vote.save!
          @comment.downvote += 1
          @comment.save!
        elsif @comment_vote.vote_type == 'upvote'
          @comment_vote.destroy!
          @comment.upvote -= 1
          @comment.downvote += 1
          @comment.save!
          @comment.comment_votes.create!(user: @user, vote_type: 'downvote')
        elsif @comment_vote.vote_type == 'downvote'
          @comment_vote.destroy!
          @comment.downvote -= 1
          @comment.save!
        end
      elsif request.request_method == "DELETE"
        if @comment_vote.new_record?
          render :json => { "status" => "403", "error" => "No vote found to delete." }, status: :forbidden and return
        elsif @comment_vote.vote_type == 'downvote'
          @comment_vote.destroy!
          @comment.downvote -= 1
          @comment.save!
        end
      end
    end

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      # format.json { render json: { "status" => "200", "message" => "Vote successfully added." }, status: :ok }
      format.json { render json: json_with_replies(@comment) , status: :ok }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def sort
    @post = Post.find(params[:id])

    case params[:sort_by]
    when "top"
      @comments = @post.comments
                  .left_joins(:comment_votes)
                  .select('comments.*, SUM(CASE WHEN comment_votes.vote_type = "upvote" THEN 1 WHEN comment_votes.vote_type = "downvote" THEN -1 ELSE 0 END) AS votes_difference')
                  .group('comments.id')
                  .order('votes_difference DESC')
      when "newest"
      @comments = @post.comments.order_by(created_at: :desc)
    else
      @comments = @post.comments.order_by(created_at: :asc)
    end

    @comment = @post.comments.build
    @sort = params[:sort_by]
    render 'posts/show'
  end

  def show
    @post = Post.find(params[:post_id])
    @coment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if @comment.user != @user
      render :json => { "status" => "403", "error" => "Only the creator can complete this action." }, status: :forbidden and return
    end

    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to post_path(@post), notice: "Comentario actualizado correctamente." }
        format.json { render json: json_with_replies(@comment) }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def new

  end

  def index
    @post = Post.find(params[:post_id])

    case params[:sort_by]
    when "top"
      @comments = @post.comments.order(Arel.sql('(upvote - downvote) DESC'))
    when "newest"
      @comments = @post.comments.order(created_at: :desc)
    else
      @comments = @post.comments.order(created_at: :asc)
    end

    @comment = @post.comments.build
    @sort = params[:sort_by]

    respond_to do |format|
      format.html { render 'posts/show' }
      format.json { render json: json_with_replies(@comments)}
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = @user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post) }
        format.json { render json: json_with_replies(@comment), include: :replies, status: :created }
      else
        format.html { render 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    if @comment.user != @user
      render :json => { "status" => "403", "error" => "Only the creator can complete this action." }, status: :forbidden and return
    end

    @post = Post.find(params[:post_id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
      format.json { render json: { "status" => "200", "message" => "Comment successfully destroyed." }, status: :ok }
    end
  end

  private

  def json_with_replies(comments)
    result = Array(comments).map do |comment|
      comment.as_json(except: [:post_id, :user_id]).merge(
        user: comment.user.as_json(only: [:id, :full_name, :email]),
        post: comment.post.as_json(only: [:id, :title]),
        is_upvoted: comment.is_upvoted(@user),
        is_downvoted: comment.is_downvoted(@user),
        is_author: comment.user == @user,
        replies: Array.wrap(json_with_replies(comment.replies)),
      )
    end

    result.length == 1 ? result.first : result
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    if request.headers[:Accept] == "application/json"
      api_key = request.headers[:HTTP_X_API_KEY]

      if api_key.nil?
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      else
        @user = User.find_by_api_key(api_key)
        if @user.nil?
          render :json => { "status" => "403", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
        end
      end
    else
      @user = current_user
    end
  end


  def comment_params
    params.require(:comment).permit(:parent_comment_id, :body)
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment wotitem" id="<%= dom_id comment %>" style="display: flex; flex-direction: column;">

    <div style="display:flex">
        <div class="comment-avatar" style="flex: 0 0 auto; margin-right: 10px">
            <% if comment.user.avatar.attached? %>
                <%= image_tag comment.user.avatar.variant(resize_to_limit: [40, 40]), class: "avatar" %>
            <% end %>
        </div>
    </div>

    <div class="comment-content" style="flex: 1 1 auto;">
        <div class="top">
            <p>
            <a style="color:#cecece; font-weight: bold;" href="<%= user_path(comment.user.id) %>">
                        <%= comment.user.full_name %>,
                </a>
                </strong>
                <span class="comment-timestamp">
                    <%= time_ago_in_words(comment.created_at) %> ago
                </span>
                <% if params[:view].present? %>
                <a>
                    to
                    <% if comment.parent_comment.nil? %>
                        <%= link_to "#{post.user.full_name}", user_path(post.user), style:"color:#cecece; font-weight: bold;"%>
                    <% else %>
                        <%= link_to "#{comment.parent_comment.user.full_name}", user_path(comment.parent_comment.user), style:"color:#cecece; font-weight: bold;"%>
                    <% end %>
                    in
                    <%= link_to "#{post.title}", post_path(post), style:"color:#cecece; font-weight: bold;"%>
                </a>
                <% end %>
            </p>

            <div class="buttons">
                <%= button_to upvote_post_comment_path(@post || post, comment), method: :put, class: "vote", style: "margin-bottom: 1em; color: #{'green' if @comment_votes_hash[comment.id] == 'upvote'}" do %>
                    <span> <%= comment.upvotes_count %> &nbsp;</span>
                    <i class="fas fa-arrow-up"></i>
                <% end %>

                <%= button_to downvote_post_comment_path(@post || post, comment), method: :put, class: "vote", style: "margin-left: 10px; color: #{'red' if @comment_votes_hash[comment.id] == 'downvote'}" do %>
                    <span> <%= comment.downvotes_count %> &nbsp;</span>
                    <i class="fas fa-arrow-down"></i>
                <% end %>
            </div>
        </div>

        <div class="body">
            <p><%= comment.body %></p>
        </div>

        <div class="actions" style="display: flex;">
        <%= link_to 'reply', user_signed_in? ? '#' : new_user_session_path, class:"#{user_signed_in? ? 'reply-link' : 'reply-link-logged-out'}", data: {comment_id: comment.id}%>
            <% if user_signed_in? && current_user == comment.user %>
            <div class="dropdown" style="position: relative;">
                <a href="#" class="dropdown-btn">more</a>
                <div class="dropdown-content" style="position: absolute; top: 1em; right: -1.2em; margin-top: 10px;">
                    <%= link_to 'edit', '#', class:'edit-comment-link', data: {comment_id: comment.id}%>
                    <a style="margin-top:-20px;">
                        <%= button_to "delete", post_comment_path(@post || post, comment), method: :delete, class:"delete-button" %>
                    </a>
                </div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="fields">
        <% if !params[:view].present? %>
            <div class="reply-comment-area" id="reply-comment-area-<%= comment.id %>" style="display: none;">
                <%= render "comments/form", comment: comment, parent_comment: comment %>
            </div>
        <% end %>

        <div class="edit-comment-area" id="edit-comment-area-<%= comment.id %>">
            <%= render "comments/edit_form", comment: comment %>
        </div>
    </div>
</div>

    <% if !params[:view].present? %>

    <div class="comment-reply" id="replies-<%= comment.id %>">
        <%= render comment.replies.order_by(@sort || 'newest') %>
    </div>

    <% end %>

<script>
document.addEventListener('DOMContentLoaded', function() {
  var editLinks = document.querySelectorAll('.edit-comment-link');

  editLinks.forEach(function(link) {

    link.addEventListener('click', function(e) {
      e.preventDefault();

      // Obtener el ID del comentario
      var commentId = this.dataset.commentId;

      var textArea = document.querySelector('#edit-comment-area-'+commentId);

      textArea.style.display = 'block';


    });
  });
});

document.addEventListener('DOMContentLoaded', function() {
  var replyLinks = document.querySelectorAll('.reply-link');

  replyLinks.forEach(function(link) {
    link.addEventListener('click', function(e) {
      e.preventDefault();

      // Obtener el ID del comentario
      var commentId = this.dataset.commentId;

      var replyArea = document.querySelector('#reply-comment-area-' + commentId);

      replyArea.style.display = 'block';

    });
  });
});

</script>

app/views/comments/_edit_form.html.erb
<%= form_with(model: comment, url: post_comment_path(comment.post, comment), method: "patch") do |form| %>
  <!-- Campos de edición del comentario -->
  <div class="form-group">
      <%= form.text_area :body, class:"form-control resizable", rows: 5, cols: 50 %>
  </div>

  <div class="form-group" style="display:flex; justify-content: right; margin-right: 10px;">
    <%= form.submit "Edit!", class: "btn btn-primary btn-rectangular" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], url: post_comments_path(@post), method:"post") do |form| %>

  <% if @comment.errors.any? %>
  <div id="error-explanation">
    <% @comment.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <% end %>


  <% if !parent_comment.nil? %>
    <%= form.hidden_field :parent_comment_id, value: parent_comment.id %>
  <% end %>

  <div class="form-group">
      <%= form.text_area :body, class:"form-control resizable", rows: 5, cols: 50 %>
  </div>

  <div class="form-group" style="display:flex; justify-content: right; margin-right: 10px;">
    <%= form.submit "Add Comment", class: "btn btn-primary btn-rectangular" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>
<% if user_signed_in? %>
<%= render "form", comment: @comment %>
<% end %>
<br>

<div>
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>