config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :magazines do
    member do
      get 'posts', to: 'magazines#posts'

      post 'subscribe', to: 'magazines#subscribe'
      delete 'subscribe', to: 'magazines#unsubscribe'
    end
  end

  resources :posts do

    post 'new_thread', on: :collection
    member do
      post 'upvote'
      post 'downvote'
      post 'boost'
      delete 'boost', action: :unboost
    end


    member do
      get 'sort_comments', to: "comments#sort"
      get 'sort_posts', to: "posts#sort"

    end
    resources :comments do

      member do
        # put 'upvote', on: :member
        # put 'downvote', on: :member
        post 'upvote'
        delete 'upvote'
        post 'downvote'
        delete 'downvote'

        get 'edit'
      end

    end
    collection do
    get 'new_link'
    get 'new_thread'
    get 'sort'
    get 'search', to: 'posts#search'

    end
  end


  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id', to: 'users/users#show', as: :user
    get 'users/:id/edit', to: 'users/users#edit', as: :edit_user
    patch '/users/:id', to: 'users/users#update'

    get 'users', to: 'users/users#index'
    get 'users/:id/comments', to: 'users/users#user_comments'
    get 'users/:id/posts', to: 'users/users#user_posts'
    get 'users/:id/boosts', to: 'users/users#user_boosts'
    put 'users/:id', to: 'users/users#update'

  end

  # Añadir la ruta para el perfil del user
  #get 'profile', to: 'users/users#show', as: 'profile'
  post 'posts', to: 'posts#create'
  delete 'posts/:id/', to: 'posts#destroy'
  put 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show'
  post 'posts/:id/upvote', to: 'posts#upvote'
  delete 'posts/:id/upvote', to: 'posts#upvote'
  put 'posts/:id/boost', to:'posts#boost'
  delete 'posts/:id/boost', to:'posts#unboost'
  post 'posts/:id/downvote', to: 'posts#downvote'
  delete 'posts/:id/downvote', to: 'posts#downvote'
  get 'posts/search', to: 'posts#search'


end

app/models/magazine.rb
class Magazine < ApplicationRecord
  validates :name, length: { minimum: 1 }
  validates :title, length: { minimum: 1 }
  has_many :posts
  has_many :comments, through: :posts
  has_and_belongs_to_many :users

  def posts_count
    posts.count
  end

  def comments_count
    comments.count
  end

  def users_count
    users.count
  end

end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
    before_action :set_user
    before_action :set_votes_hash
    before_action :set_magazine, only: %i[show update]

    def subscribe
      @magazine = Magazine.find(params[:id])
      if @user.magazines.include?(@magazine)
        respond_to do |format|
          format.html { redirect_to @magazine, notice: "You are already subscribed." }
          format.json { render json: { "status" => "409", "message" => "Already subscribed." }, status: :conflict }
        end
      else
        @user.magazines << @magazine
        respond_to do |format|
          format.html { redirect_to @magazine }
          format.json { render json: { "status" => "200", "message" => "Successfully subscribed." }, status: :ok }
        end
      end
    end

    def unsubscribe
      @magazine = Magazine.find(params[:id])
      if @user.magazines.include?(@magazine)
        @user.magazines.delete(@magazine)
        respond_to do |format|
          format.html { redirect_to magazines_path }
          format.json { render json: { "status" => "200", "message" => "Successfully unsubscribed." }, status: :ok }
        end
      else
        respond_to do |format|
          format.html { redirect_to @magazine, notice: "You are not subscribed." }
          format.json { render json: { "status" => "409", "message" => "Not subscribed." }, status: :conflict }
        end
      end
    end

    def set_votes_hash
      if user_signed_in?
        @comment_votes_hash = current_user.comment_votes.index_by(&:comment_id).transform_values(&:vote_type)
        @votes_hash = current_user.votes.index_by(&:post_id).transform_values(&:vote_type)
        @boosted_posts = current_user.boosts.pluck(:post_id)
      else
        @votes_hash = {}
        @comment_votes_hash = {}
        @boosted_posts = {}
      end
    end

    # GET /magazines or /magazines.json
    def index
      sort_by = params[:sort_by]
      case sort_by
      when "threads"
        @magazines = Magazine.left_joins(:posts).group(:id).order('COUNT(posts.id) DESC')
      when "comments"
        @magazines = Magazine.left_joins(:comments).group(:id).order('COUNT(comments.id) DESC')
      when "subscribers"
        @magazines = Magazine.left_joins(:users).group(:id).order('COUNT(users.id) DESC')
      else
        @magazines = Magazine.order(created_at: :desc)
      end

      respond_to do |format|
        format.html

        format.json {render json: magazines_with_info}
      end
    end

    # GET /magazines/1 or /magazines/1.json
    def show
      @posts = @magazine.posts.order_by(params[:sort_by] ? params[:sort_by] : [:created_at, :desc])

      respond_to do |format|
        format.html

        format.json {render json: @magazine.as_json.merge({threads: @magazine.posts.count, comments: @magazine.posts.left_joins(:comments).count, subscribers: @magazine.users.count, isSubscribed: @user.magazines.include?(@magazine)})}
      end

    end

    def posts
  @magazine = Magazine.find(params[:id])
  @posts = @magazine.posts.order_by(params[:sort_by] ? params[:sort_by] : [:created_at, :desc])

  respond_to do |format|
    format.json do
      @posts = @posts.map do |post|
        post_json = post.as_json(methods: [:upvotes_count, :downvotes_count, :comments_count], except: [:magazine_id, :user_id]).merge(
          is_upvoted: post.is_upvoted(@user),
          is_downvoted: post.is_downvoted(@user),
          is_boosted: post.is_boosted(@user)
        )

        if post.magazine.present?
          post_json[:magazine] = post.magazine.as_json(only: [:id, :title, :description])
        end

        if post.user.present?
          post_json[:user] = post.user.as_json(only: [:id, :full_name, :email])
        end

        post_json
      end
      render json: { posts: @posts }
    end
  end
end


    # GET /magazines/new
    def new
      @magazine = Magazine.new
    end

    # magazine /magazines or /magazines.json
    def create
      @magazine = Magazine.new(magazine_params)

      respond_to do |format|
        if @magazine.save
          format.html { redirect_to magazines_url, notice: "Magazine was successfully created." }
          format.json { render json: @magazine }
        else
          format.html { redirect_to magazines_url, notice: @magazine.errors.full_messages.join(", ") }
          format.json { render json: @magazine.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /magazines/1 or /magazines/1.json
    def update
      respond_to do |format|
        if @magazine.update(magazine_params)
          format.html { redirect_to magazine_url(@magazine), notice: "Magazine was successfully updated." }
          format.json { render :show, status: :ok, location: @magazine }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @magazine.errors, status: :unprocessable_entity }
        end
      end
    end



    private
      # Use callbacks to share common setup or constraints between actions.
      def set_magazine
        @magazine = Magazine.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def magazine_params
        params.require(:magazine).permit(:name, :title, :description, :rules)
      end


      def magazines_with_info
        @magazines.map do |magazine|
          magazine.as_json.merge({threads: magazine.posts.count, comments: magazine.posts.left_joins(:comments).count, subscribers: magazine.users.count, isSubscribed: @user.magazines.include?(magazine)})
        end
      end

      def set_user
        if request.headers[:Accept] == "application/json"
          api_key = request.headers[:HTTP_X_API_KEY]

        if api_key.nil?
          render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
        else
          @user = User.find_by_api_key(api_key)
          if @user.nil?
            render :json => { "status" => "403", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
          end
        end
        else
          @user = current_user
        end
      end
end

app/views/magazines/_form.html.erb
<%= form_with(model: @magazine, url: magazines_path, local: true, html: { class: "post-form" }) do |form| %>

<% if @magazine.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@magazine.errors.count, "error") %> han ocurrido al crear la revista:</h2>
     <ul>
     <% @magazine.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

  <div class="form-group">
    <%= form.label :name, "Name:", class:"form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title, "Title:", class:"form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description:", class:"form-label" %>
    <%= form.text_area :description, rows: 3, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rules, "Rules:" , class:"form-label" %>
    <%= form.text_area :rules, rows: 3, class: "form-control" %>
  </div>

  <div class="form-group text-right">
    <%= form.submit "Add new magazine!", class: "btn btn-primary btn-rectangular" %>
  </div>
<% end %>

app/views/magazines/_magazine.html.erb
<div class="wotitem">
  <div class="post-header">
    <!-- Informacion de la revista -->
    <div class="magazine-info">
        <h2>Nombre: <%= link_to magazine.name, magazine %></h2>
        <h2>Título: <%= magazine.title %></h2>
      <p>
        <strong>Sobre la revista:</strong>
        <br>
        <%= magazine.description %>
      </p>
      <p>
        <strong>Reglas:</strong>
        <br>
        <%= magazine.rules %>
      </p>
    </div>
  </div>
</div>

app/views/magazines/index.html.erb
<div class="sub-navbar">
  <div>
    <%= link_to "Most Threads", magazines_path(sort_by: "threads") %>
    <%= link_to "Most Comments", magazines_path(sort_by: "comments") %>
    <%= link_to "Most Subscribers", magazines_path(sort_by: "subscribers") %>
  </div>
</div>

<body class="wotbody">
  <div class="wotitem">
  <table class="magazine-table">
    <thead>
      <tr>
        <th class="magazine-th">Name</th>
        <th class="magazine-th"># Threads</th>
        <th class="magazine-th"># Comments</th>
        <%
=begin%>
 <th class="magazine-th"># Subscribers</th>
<%
=end%>
        <th class="magazine-th">Subscribe/Unsubscribe</th>
      </tr>
    </thead>
    <tbody>
      <% @magazines.each do |magazine| %>
        <tr>
          <td class="magazine-td"><strong><%= link_to magazine.name, magazine, style: "color: white;" %></strong></td>
          <td class="magazine-td"><%= magazine.posts.count %></td>
          <td class="magazine-td"><%= magazine.comments.count %></td>
          <%
=begin%>
 <td class="magazine-td"><%= magazine.users.size %></td>
<%
=end%>
          <td class="magazine-td" style="display: flex; flex-direction: row; justify-content: center;">
            <div class="user_actions_mag">
              <i style="margin: 10px 5px 5px 5px;" class="fas fa-users"></i> &nbsp <%= magazine.users.size %> &nbsp
            </div>
            <div class="user_actions_mag">
              <% if user_signed_in? %>
                <% if current_user.magazines.include?(magazine) %>
                  <%= button_to "Unsubscribe", subscribe_magazine_path(magazine.id), method: :delete, class: 'btn btn-primary btn-rectangular-mag' %>
                <% else %>
                  <%= button_to "Subscribe", subscribe_magazine_path(magazine.id), method: :post, class: 'btn btn-primary btn-rectangular-mag' %>
                <% end %>
              <% else %>
                <%= button_to "Subscribe", new_user_session_path, method: :get, class: 'btn btn-primary btn-rectangular-mag' %>
              <% end %>
            <div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

</body>
<hr>
<footer>
</footer>

app/views/magazines/new.html.erb
<div class="sub-navbar"  style ="height: 35px";>
  <div>
    <span class="navbar-title">ADD NEW</span>
    <a href="/posts/new_link" class="navbar-item">link</a>
    <a href="/posts/new_thread" class="navbar-item">thread</a>
    <a href="/magazines/new" class="navbar-item">magazine</a>
  </div>
</div>

<div class="wotitem">
  <div class="post-header">
    <!-- Contenido de la revista -->
    <div class="post-content" style="color: white;">
      <%= render 'form' %>
      <div class="post-actions" style="text-align: center;">
        <%= link_to 'Back', magazines_path, class: 'btn btn-primary btn-rectangular' %>
      </div>
    </div>
  </div>
</div>

app/views/magazines/show.html.erb
<div class="container">
    <div class="wotitem">
      <h2><%= @magazine.name %></h2>
      <strong><p>@<%= @magazine.title %>@talkify</p></strong>
      <strong><p>Description:</p></strong>
      <p><%= @magazine.description %></p>
      <strong><p>Rules:</p></strong>
      <p><%= @magazine.rules %></p>
      <% if user_signed_in? %>
        <% if current_user.magazines.include?(@magazine) %>
          <%= button_to "Unsubscribe", subscribe_magazine_path(@magazine), method: :delete, class: 'btn btn-primary btn-rectangular' %>
        <% else %>
          <%= button_to "Subscribe", subscribe_magazine_path(@magazine), method: :post, class: 'btn btn-primary btn-rectangular' %>
        <% end %>
      <% else %>
        <%= button_to "Subscribe", new_user_session_path, method: :get, class: 'btn btn-primary btn-rectangular' %>
      <% end %>
    </div>

    <div class="wotitem">
      <p><strong>Created: </strong><%= time_ago_in_words(@magazine.created_at) %> ago</p>
      <p><strong>Subscribers: </strong><%= @magazine.users.count %></p>
      <p><strong>Threads: </strong><%= @magazine.posts.count %></p>
      <p><strong>Comments: </strong><%= @magazine.comments.count %></p>
    </div>

    <div class="sub-navbar wotitem">
      <div>
        <%= link_to "Top", magazine_path(@magazine, sort_by: "top") %>
        <%= link_to "Newest", @magazine %>
        <%= link_to "Commented", magazine_path(@magazine, sort_by: "commented") %>
      </div>
    </div>

    <div id="posts">
    <% @posts.each do |post| %>
      <% if post.id %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>
</div>