config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  resources :magazines do
    member do
      get 'posts', to: 'magazines#posts'

      post 'subscribe', to: 'magazines#subscribe'
      delete 'subscribe', to: 'magazines#unsubscribe'
    end
  end

  resources :posts do

    post 'new_thread', on: :collection
    member do
      post 'upvote'
      post 'downvote'
      post 'boost'
      delete 'boost', action: :unboost
    end


    member do
      get 'sort_comments', to: "comments#sort"
      get 'sort_posts', to: "posts#sort"

    end
    resources :comments do

      member do
        # put 'upvote', on: :member
        # put 'downvote', on: :member
        post 'upvote'
        delete 'upvote'
        post 'downvote'
        delete 'downvote'

        get 'edit'
      end

    end
    collection do
    get 'new_link'
    get 'new_thread'
    get 'sort'
    get 'search', to: 'posts#search'

    end
  end


  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/:id', to: 'users/users#show', as: :user
    get 'users/:id/edit', to: 'users/users#edit', as: :edit_user
    patch '/users/:id', to: 'users/users#update'

    get 'users', to: 'users/users#index'
    get 'users/:id/comments', to: 'users/users#user_comments'
    get 'users/:id/posts', to: 'users/users#user_posts'
    get 'users/:id/boosts', to: 'users/users#user_boosts'
    put 'users/:id', to: 'users/users#update'

  end

  # Añadir la ruta para el perfil del user
  #get 'profile', to: 'users/users#show', as: 'profile'
  post 'posts', to: 'posts#create'
  delete 'posts/:id/', to: 'posts#destroy'
  put 'posts/:id', to: 'posts#update'
  get 'posts/:id', to: 'posts#show'
  post 'posts/:id/upvote', to: 'posts#upvote'
  delete 'posts/:id/upvote', to: 'posts#upvote'
  put 'posts/:id/boost', to:'posts#boost'
  delete 'posts/:id/boost', to:'posts#unboost'
  post 'posts/:id/downvote', to: 'posts#downvote'
  delete 'posts/:id/downvote', to: 'posts#downvote'
  get 'posts/search', to: 'posts#search'


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :magazine
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :boosts, dependent: :destroy



  validates :title, presence: true, length: { minimum: 4 }
  validates :url, presence: true, if: -> { link }
  validates :magazine_id, presence: true


  def comments_count
  comments.count
  end


def self.order_by(sort_by)
    case sort_by
    when "top"
      select('posts.*,
              COALESCE(SUM(CASE WHEN votes.vote_type = \'upvote\' THEN 1 ELSE 0 END), 0) -
              COALESCE(SUM(CASE WHEN votes.vote_type = \'downvote\' THEN 1 ELSE 0 END), 0) AS score')
        .left_joins(:votes)
        .group('posts.id')
        .order('score DESC')
    when "newest"
      order(created_at: :desc)
    when "commented"
      select('posts.*, COUNT(comments.id) AS comments_count')
        .left_joins(:comments)
        .group('posts.id')
        .order('comments_count DESC, created_at DESC')
    else
      order(created_at: :desc) # Ordenar por defecto por fecha de creación
    end
  end

  def upvotes_count
    votes.where(vote_type: 'upvote').count
  end

  def downvotes_count
    votes.where(vote_type: 'downvote').count
  end

  def is_upvoted(user)
    votes.where(vote_type: 'upvote', user_id: user.id).exists?
  end

  def is_downvoted(user)
    votes.where(vote_type: 'downvote', user_id: user.id).exists?
  end

  def is_boosted(user)
    boosts.where(user_id: user.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_votes_hash
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :boost], except: [:search]

  def set_votes_hash
    if @user.present?
      @comment_votes_hash = @user.comment_votes.index_by(&:comment_id).transform_values(&:vote_type)
      @votes_hash = @user.votes.index_by(&:post_id).transform_values(&:vote_type)
      @boosted_posts = @user.boosts.pluck(:post_id)
    elsif user_signed_in?
      @comment_votes_hash = current_user.comment_votes.index_by(&:comment_id).transform_values(&:vote_type)
      @votes_hash = current_user.votes.index_by(&:post_id).transform_values(&:vote_type)
      @boosted_posts = current_user.boosts.pluck(:post_id)
    else
      @votes_hash = {}
      @comment_votes_hash = {}
      @boosted_posts = {}
    end
  end


 def boost
  @post = Post.find(params[:id])
  @boost = Boost.find_or_initialize_by(post: @post, user: @user)

  if @boost.new_record?
    @boost.save!
    boost_status = "boosted"
    status = :ok
  else
    boost_status = "already boosted"
    status = :conflict
  end

  post_json = @post.as_json(
    methods: [:upvotes_count, :downvotes_count, :comments_count],
    except: [:magazine_id, :user_id]
  ).merge(
    is_upvoted: @post.is_upvoted(@user),
    is_downvoted: @post.is_downvoted(@user),
    is_boosted: @post.is_boosted(@user)
  )

  post_json[:magazine] = @post.magazine.as_json(only: [:id, :title, :description]) if @post.magazine.present?
  post_json[:user] = @post.user.as_json(only: [:id, :full_name, :email]) if @post.user.present?

  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.json { render json: { post: post_json, boost_status: boost_status }, status: status }
  end
end


def unboost
  @post = Post.find(params[:id])
  @boost = Boost.find_by(post: @post, user: @user)

  if @boost.present?
    @boost.destroy!
    boost_status = "unboosted"
    status = :ok
  else
    boost_status = "not boosted"
    status = :conflict
  end

  post_json = @post.as_json(
    methods: [:upvotes_count, :downvotes_count, :comments_count],
    except: [:magazine_id, :user_id]
  ).merge(
    is_upvoted: @post.is_upvoted(@user),
    is_downvoted: @post.is_downvoted(@user),
    is_boosted: @post.is_boosted(@user)
  )

  post_json[:magazine] = @post.magazine.as_json(only: [:id, :title, :description]) if @post.magazine.present?
  post_json[:user] = @post.user.as_json(only: [:id, :full_name, :email]) if @post.user.present?

  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.json { render json: { post: post_json, boost_status: boost_status }, status: status }
  end
end


  def like
    @post.likes += 1
    @post.save

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

def upvote
  @post = Post.find(params[:id])
  message = ''
  ActiveRecord::Base.transaction do
    @vote = @post.votes.find_or_initialize_by(user: @user)

    if @vote.new_record? && request.method == "POST"
      @vote.vote_type = 'upvote'
      @vote.save!
      status = :ok
      message = "Vote successfully added."
    elsif @vote.new_record? && request.method == "DELETE"
      status = :conflict
      message = "No vote found to delete."
    elsif @vote.vote_type == 'downvote'
      @vote.destroy!
      @post.votes.create!(user: @user, vote_type: 'upvote')
      status = :ok
      message = "Vote successfully changed to upvote."
    elsif @vote.vote_type == 'upvote' && request.method == "POST"
      status = :conflict
      @vote.destroy!
      message = "Already upvoted."
    elsif @vote.vote_type == 'upvote' && request.method == "DELETE"
      @vote.destroy!
      status = :ok
      message = "Vote successfully removed."
    end
  end

  post_json = @post.as_json(
    methods: [:upvotes_count, :downvotes_count, :comments_count],
    except: [:magazine_id, :user_id]
  ).merge(
    is_upvoted: @post.is_upvoted(@user),
    is_downvoted: @post.is_downvoted(@user),
    is_boosted: @post.is_boosted(@user)
  )

  post_json[:magazine] = @post.magazine.as_json(only: [:id, :title, :description]) if @post.magazine.present?
  post_json[:user] = @post.user.as_json(only: [:id, :full_name, :email]) if @post.user.present?

  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.json { render json: { post: post_json, status: status, message: message }, status: status }
  end
end



 def downvote
  @post = Post.find(params[:id])
  message = ''
  ActiveRecord::Base.transaction do
    @vote = @post.votes.find_or_initialize_by(user: @user)

    if @vote.new_record? && request.method == "POST"
      @vote.vote_type = 'downvote'
      @vote.save!
      status = :ok
      message = "Vote successfully added."
    elsif @vote.new_record? && request.method == "DELETE"
      status = :conflict
      message = "No vote found to delete."
    elsif @vote.vote_type == 'downvote' && request.method == "DELETE"
      @vote.destroy!
      status = :ok
      message = "Vote successfully removed."
    elsif @vote.vote_type == 'upvote' && request.method == "DELETE"
      status = :conflict
      message = "No downvote found to delete."
    elsif @vote.vote_type == 'upvote'
      @vote.destroy!
      @post.votes.create!(user: @user, vote_type: 'downvote')
      status = :ok
      message = "Vote successfully changed to downvote."
  elsif @vote.vote_type == 'downvote' && request.method == "POST"
      status = :conflict
      @vote.destroy!
      message = "Already downvoted."
    end
  end

  post_json = @post.as_json(
    methods: [:upvotes_count, :downvotes_count, :comments_count],
    except: [:magazine_id, :user_id]
  ).merge(
    is_upvoted: @post.is_upvoted(@user),
    is_downvoted: @post.is_downvoted(@user),
    is_boosted: @post.is_boosted(@user)
  )

  post_json[:magazine] = @post.magazine.as_json(only: [:id, :title, :description]) if @post.magazine.present?
  post_json[:user] = @post.user.as_json(only: [:id, :full_name, :email]) if @post.user.present?

  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.json { render json: { post: post_json, status: status, message: message }, status: status }
  end
end



  def sort
    @posts = Post.order_by(params[:sort_by])
    render :index
  end

def search
  @query = params[:query]
  @posts = Post.where("title LIKE :query OR body LIKE :query", query: "%#{@query}%")

     respond_to do |format|
      format.html
      format.json do
        if @posts.present?
          @posts = @posts.map do |post|
        post_json = post.as_json(methods: [:upvotes_count, :downvotes_count, :comments_count], except: [:magazine_id, :user_id]).merge(
          is_upvoted: post.is_upvoted(@user),
          is_downvoted: post.is_downvoted(@user),
          is_boosted: post.is_boosted(@user)
        )

        if post.magazine.present?
          post_json[:magazine] = post.magazine.as_json(only: [:id, :title, :description])
        end

        if post.user.present?
          post_json[:user] = post.user.as_json(only: [:id, :full_name, :email])
        end

        post_json
      end
        render json: { posts: @posts }
        else
          render json: { error: "There are no posts that match the query" }, status: :not_found
        end
    end
  end
end


def index
  @posts = Post.all

  # Aplicar filtro si está presente
  case params[:filter]
  when "links"
    @posts = @posts.where(link: true)
  when "threads"
    @posts = @posts.where(link: false)
  else
    # Si el filtro no es "links" ni "threads", no aplicamos ningún filtro
  end

  # Aplicar ordenación si está presente
  if params[:sort_by]
    @posts = @posts.order_by(params[:sort_by])
  else
    @posts = @posts.order_by("newest")
  end

  respond_to do |format|
    format.html
    format.json do
      @posts = @posts.map do |post|
        post_json = post.as_json(methods: [:upvotes_count, :downvotes_count, :comments_count], except: [:magazine_id, :user_id]).merge(
          is_upvoted: post.is_upvoted(@user),
          is_downvoted: post.is_downvoted(@user),
          is_boosted: post.is_boosted(@user)
        )

        if post.magazine.present?
          post_json[:magazine] = post.magazine.as_json(only: [:id, :title, :description])
        end

        if post.user.present?
          post_json[:user] = post.user.as_json(only: [:id, :full_name, :email])
        end

        post_json
      end
      render json: { posts: @posts }
    end
  end
end



def show
  @post = Post.find(params[:id])

  respond_to do |format|
    format.html do
      if request.headers[:Accept] != "application/json"
        @comment = @post.comments.build
      end
      @comments = @post.comments.includes(:replies)
    end

    format.json do
      post_json = @post.as_json(
        methods: [:upvotes_count, :downvotes_count, :comments_count],
        except: [:magazine_id, :user_id]
      ).merge(
        is_upvoted: @post.is_upvoted(@user),
        is_downvoted: @post.is_downvoted(@user),
        is_boosted: @post.is_boosted(@user)
      )

      if @post.magazine.present?
        post_json[:magazine] = @post.magazine.as_json(only: [:id, :title, :description])
      end

      if @post.user.present?
        post_json[:user] = @post.user.as_json(only: [:id, :full_name, :email])
      end

      render json: { post: post_json, comments: { include: :replies } }
    end
  end
end


  def new
    @post = Post.new(link: params[:link] == 'true')
    @magazines = Magazine.all.order(:name)
  end

  def new_link
    @post = Post.new(link: true)
    @magazines = Magazine.all.order(:name)  # Asumiendo que cada revista tiene un atributo 'name'
  end

  def new_thread
    @post = Post.new(link: false)
    @magazines = Magazine.all.order(:name)  # Asumiendo que cada revista tiene un atributo 'name'
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: posts_path, local: true, html: { class: "post-form" }) do |form| %>

<% if @post.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@post.errors.count, "error") %> han ocurrido al crear el post:</h2>
     <ul>
     <% @post.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

  <div class="form-group">
    <%= form.label :title, "Title:", class:"form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url, "URL:", class:"form-label" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body, "Body:" , class:"form-label" %>
    <%= form.text_area :body, rows: 2, class: "form-control" %>
  </div>

<div class="form-group">
  <%= form.label :magazine_id, "Magazine:", class: "form-label" %>
  <%= form.collection_select :magazine_id, @magazines, :id, :name, {}, {class: "form-control"} %>
</div>


  <div class="form-group text-right">
    <%= form.submit "Add new link!", class: "btn btn-primary btn-rectangular" %>
  </div>

 <%= form.hidden_field :user_id, value: current_user.id %>
<%= form.hidden_field :link %>
<% end %>

app/views/posts/_post.html.erb
<div class="wotitem">
  <div class="post-header">


<div class="vote-buttons">
  <%= button_to upvote_post_path(post), method: :post, class: "vote", style: "margin-bottom: 1em; color: #{'green' if @votes_hash[post.id] == 'upvote'}" do %>
  <span> <%= post.upvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-up" style="color: #{'green' if @votes_hash[post.id] == 'upvote'}"></i>
<% end %>

<%= button_to downvote_post_path(post), method: :post, class: "vote", style: "color: #{'red' if @votes_hash[post.id] == 'downvote'}" do %>
  <span> <%= post.downvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-down" style="color: #{'red' if @votes_hash[post.id] == 'downvote'}"></i>
<% end %>

<% unless user_signed_in? %>
  <script>
    document.querySelectorAll('.vote').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.location.href = '<%= new_user_session_path %>';
      });
    });
  </script>
<% end %>
</div>



    <!-- Imagen -->
    <!-- <div class="no-image">
      <%= link_to post_path(post) do %>
        <i class="fas fa-comment-alt"></i>
      <% end %>
    </div>-->

    <!-- Contenido del post -->
    <div class="post-content" style = "margin-left: 20px;">

    <div class="text-container">
       <span class="first-part">
        <h2>
          <%= link_to post.title, post_path(post), style: "color: white;" %>
          <% if post.link? %>
            <span style="font-size: 14px;">
              (<%= link_to post.url, post.url, target: "_blank", style: "color: white;" %>)
            </span>
          <% end %>
        </h2>

        </span>

      </div>

  <div class="text-container" style="color:#cecece; font-size: 14px;">
    <p> <strong><a style="color:#cecece;" href="<%= user_path(post.user) %>">
                    <%= post.user.full_name %>
            </a>
            </strong> <%= time_ago_in_words(post.created_at) %> ago to magazine <strong><%= link_to post.magazine.name, magazine_path(post.magazine), style: "color: white;" %></strong></p>
    </div>





<div class="comments-count" style="color: white;font-size: 14px;">
      <%= link_to pluralize(post.comments_count, 'comment'), post_path(post), class: 'comment-link', style: "text-decoration: underline; color: white;" %>
         <% if @boosted_posts.include?(post.id) %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= post.id %>);">boost(1)</span>
      <%= form_with model: @post, url: boost_post_path(post), method: :delete, id: "boost_form#{post.id}", style: "display: none;" do |form| %> <% end %>
  <% else %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= post.id %>);">boost</span>
    <%= form_with model: @post, url: boost_post_path(post), method: :put, id: "boost_form#{post.id}", style: "display: none;" do |form| %> <% end %>
  <% end %>



  <% unless user_signed_in? %>
    <script>
      document.querySelectorAll('.boost-link').forEach(function(link) {
        link.addEventListener('click', function(e) {
          e.preventDefault();
          window.location.href = '<%= new_user_session_path %>';
        });
      });
    </script>
  <% end %>
    </div>
    </div>
</div>

<script>
  function boostPost(postId) {
    document.getElementById('boost_form' + postId).submit();
  }
</script>


</div>

app/views/posts/edit.html.erb
<div class="wotitem">
  <div class="post-header">




<div class="vote-buttons">
  <%= button_to upvote_post_path(@post), method: :put, class: "vote", style: "margin-bottom: 1em; color: #{'green' if @votes_hash[@post.id] == 'upvote'}" do %>
  <span> <%= @post.upvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-up" style="color: #{'green' if @votes_hash[post.id] == 'upvote'}"></i>
<% end %>

<%= button_to downvote_post_path(@post), method: :put, class: "vote", style: "color: #{'red' if @votes_hash[@post.id] == 'downvote'}" do %>
  <span> <%= @post.downvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-down" style="color: #{'red' if @votes_hash[post.id] == 'downvote'}"></i>
<% end %>

<% unless user_signed_in? %>
  <script>
    document.querySelectorAll('.vote').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.location.href = '<%= new_user_session_path %>';
      });
    });
  </script>
<% end %>
</div>


    <!-- Contenido del post -->
   <!-- Contenido del post -->
    <div style="margin-left:10px;" class="post-content">
        <div class="text-container">
        <span class="first-part"><h2><%= link_to @post.title,@post.url , target: "_blank", style: "color: white;" %></h2></span>
         <p> <strong><a style="color:#cecece; font-size: 14px;" href="<%= user_path(@post.user) %>">
                    <%= @post.user.full_name %>
            </a>
            </strong> <%= time_ago_in_words(@post.created_at) %> ago  </strong></p>
    </div>
      <div class="comments-count" style="color: white;font-size: 14px;">
      <%= link_to pluralize(@post.comments_count, 'comment'), post_path(@post), class: 'comment-link', style: "text-decoration: underline; color: white;" %>
         <% if @boosted_posts.include?(@post.id) %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= @post.id %>);">boost(1)</span>
  <% else %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= @post.id %>);">boost</span>
  <% end %>

  <%= form_with model: @post, url: boost_post_path(@post), method: :post, id: "boost_form#{@post.id}", style: "display: none;" do |form| %>
  <% end %>

  <% unless user_signed_in? %>
    <script>
      document.querySelectorAll('.boost-link').forEach(function(link) {
        link.addEventListener('click', function(e) {
          e.preventDefault();
          window.location.href = '<%= new_user_session_path %>';
        });
      });
    </script>
  <% end %>
    </div>
      <p> <%= @post.body %></p>

    </div>


  <!-- Enlaces para editar y eliminar el post -->
    <% if user_signed_in? && current_user == @post.user %>
    <div class="post-actions">
    <%= link_to 'Editar', edit_post_path(@post), class: 'btn btn-primary btn-rectangular'%>
    <hr style="opacity: 0%;">
    <%= button_to 'Eliminar', @post, method: :delete, class: 'btn btn-danger btn-rectangular' %>
    </div>
    <% end %>
  </div>




<script>
  function boostPost(postId) {
    document.getElementById('boost_form' + postId).submit();
  }
</script>

  </div>

  <div class="post-header">
    <!-- Contenido del post -->
    <div class="post-content" style ="color: white;">
        <%= render 'formedit' %>
    </div>
    </div>

app/views/posts/index.html.erb
<!-- Wall of Posts main view -->
<div class="sub-navbar">
 <div>
    <%= link_to "Top", sort_posts_path(sort_by: "top") %>
    <%= link_to "Newest", sort_posts_path(sort_by: "newest") %>
    <%= link_to "Commented", sort_posts_path(sort_by: "commented") %>
  </div>
  <div class="navbar-icons">
    <a href="#"><i class="fas fa-eye"></i></a>
    <a href="#"><i class="fas fa-clock"></i></a>
    <div class="dropdown">
      <a href="#" class="dropdown-btn"><i class="fas fa-filter" style="color: #fff;"></i></a>
        <div class="dropdown-content" style="top: 7.42rem; right: 5rem;">
          <%= link_to "All", posts_path %>
          <%= link_to "Links", posts_path(filter: "links") %>
          <%= link_to "Threads", posts_path(filter: "threads") %>
        </div>
    </div>
  </div>
</div>
<body class="wotbody">

  <div id="tweets">
    <% @posts.each do |post| %>
      <% if post.id %>
         <div>
          <%= render post %>
      </div>
      <% end %>
    <% end %>
  </div>

</body>
<hr>
<footer>
</footer>

app/views/posts/new.html.erb
 <div class="sub-navbar"  style ="height: 35px";>
    <div>
      <span class="navbar-title">ADD NEW</span>
      <a href="/posts/new_link" class="navbar-item">link</a>
      <a href="/posts/new_thread" class="navbar-item">thread</a>
      <a href="/magazines/new" class="navbar-item">magazine</a>

    </div>
  </div>

  <div class="wotitem">
    <div class="post-header">
      <!-- Contenido del post -->
      <div class="post-content" style="color: white;">
        <%= render 'form' %>
        <div class="post-actions" style="text-align: center;">
        <%= link_to 'Back', posts_path, class: 'btn btn-primary btn-rectangular' %>      </div>
      </div>
    </div>
  </div>

app/views/posts/show.html.erb
<div class="wotitem">
  <div class="post-header">

<div class="vote-buttons">
  <%= button_to upvote_post_path(@post), method: :put, class: "vote", style: "margin-bottom: 1em; color: #{'green' if @votes_hash[@post.id] == 'upvote'}" do %>
  <span> <%= @post.upvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-up" style="color: #{'green' if @votes_hash[post.id] == 'upvote'}"></i>
<% end %>

<%= button_to downvote_post_path(@post), method: :put, class: "vote", style: "color: #{'red' if @votes_hash[@post.id] == 'downvote'}" do %>
  <span> <%= @post.downvotes_count %> &nbsp;</span>
  <i class="fas fa-arrow-down" style="color: #{'red' if @votes_hash[post.id] == 'downvote'}"></i>
<% end %>

<% unless user_signed_in? %>
  <script>
    document.querySelectorAll('.vote').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.location.href = '<%= new_user_session_path %>';
      });
    });
  </script>
<% end %>
</div>


    <!-- Contenido del post -->
    <div style="margin-left:10px;" class="post-content">
        <div class="text-container">
        <span class="first-part"><h2><%= link_to @post.title,@post.url , target: "_blank", style: "color: white;" %></h2></span>
         <p> <strong><a style="color:#cecece; font-size: 14px;" href="<%= user_path(@post.user) %>">
                    <%= @post.user.full_name %>
            </a>
            </strong> <%= time_ago_in_words(@post.created_at) %> ago  </strong></p>
    </div>
      <div class="comments-count" style="color: white;font-size: 14px;">
      <%= link_to pluralize(@post.comments_count, 'comment'), post_path(@post), class: 'comment-link', style: "text-decoration: underline; color: white;" %>
         <% if @boosted_posts.include?(@post.id) %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= @post.id %>);">boost(1)</span>
  <% else %>
    <span class="boost-link" style="text-decoration: underline; color: white;" onclick="boostPost(<%= @post.id %>);">boost</span>
  <% end %>

  <%= form_with model: @post, url: boost_post_path(@post), method: :post, id: "boost_form#{@post.id}", style: "display: none;" do |form| %>
  <% end %>

  <% unless user_signed_in? %>
    <script>
      document.querySelectorAll('.boost-link').forEach(function(link) {
        link.addEventListener('click', function(e) {
          e.preventDefault();
          window.location.href = '<%= new_user_session_path %>';
        });
      });
    </script>
  <% end %>
    </div>
      <p> <%= @post.body %></p>

    </div>



  <!-- Enlaces para editar y eliminar el post -->
    <% if user_signed_in? && current_user == @post.user %>
    <div class="post-actions">
    <%= link_to 'Editar', edit_post_path(@post), class: 'btn btn-primary btn-rectangular'%>
    <hr style="opacity: 0%;">
    <%= button_to 'Eliminar', @post, method: :delete, class: 'btn btn-danger btn-rectangular' %>
    </div>
    <% end %>
  </div>

  </div>
</div>

<div class="sub-navbar wotitem">
  <div>
    <%= link_to "Top", sort_comments_post_path(@post, sort_by: "top") %>
    <%= link_to "Newest", sort_comments_post_path(@post, sort_by: "newest") %>
    <%= link_to "Oldest", sort_comments_post_path(@post, sort_by: "oldest") %>
  </div>
</div>


<div class="wotitem" name="new-comment">

  <%= render "comments/form", post: @post, comment: @comment, parent_comment: nil %>


</div>

<div name="show-comments">
  <%= render @comments.where(parent_comment_id: nil) %>
</div>

<script>
  function boostPost(postId) {
    document.getElementById('boost_form' + postId).submit();
  }
</script>